Raghav/homepage
InvestoBull/stock-price-prediction pull request #37
Opened 2021-06-30 03:09 UTC by raghavthakur

<img width="1195" alt="Screen Shot 2021-06-29 at 8 05 42 PM" src="https://user-images.githubusercontent.com/7005506/123896065-b807ed80-d915-11eb-8ae5-4623b76d44c6.png">

- search bar
- autocomplete
- clickable symbols
- watchlist buttons
- refactored for backend

2021-07-01 20:05 UTC, HGoyal09 requested changes

2021-07-01 20:05 UTC, HGoyal09 commented on src/pages/Home/index.jsx
> +        <StockTableCard/>
Accessibility issues in the dark mode 
![image](https://user-images.githubusercontent.com/31973210/124179139-39bb6080-da67-11eb-98df-fb9d13526994.png)

2021-07-01 20:05 UTC, HGoyal09 commented on src/pages/Home/index.jsx
> +        <StockSearchBar/>
It would be nice to align the search bar with the stocks in the page 
![image](https://user-images.githubusercontent.com/31973210/124179301-83a44680-da67-11eb-8e45-681401b1bdd4.png)

2021-07-01 20:05 UTC, HGoyal09 commented on src/pages/Home/index.jsx
>          <Heading>Home</Heading>
We can call the page something more descriptive than home

2021-07-01 20:05 UTC, HGoyal09 commented on src/components/StockTable/index.jsx
> +    const stocks = stockInfo;
This is the incorrect way to fetch data. Please use context API here

2021-07-01 20:05 UTC, HGoyal09 commented on src/components/StockTable/index.jsx
> +                        <Th></Th>
Not sure why the 1st 3 columns do not have a heading 
![image](https://user-images.githubusercontent.com/31973210/124179555-db42b200-da67-11eb-9058-aa42fae30ec8.png)

2021-07-01 20:05 UTC, HGoyal09 commented on src/components/WatchlistButton/index.jsx
> +        <Button leftIcon={<BsStar />} colorScheme='green' variant='outline' />
I think the watchlist button can be smaller 
It might be better to center the star 
![image](https://user-images.githubusercontent.com/31973210/124179688-07f6c980-da68-11eb-8203-f73ad7988901.png)

2021-07-01 20:05 UTC, HGoyal09 commented on src/components/StockSearchBar/index.jsx
> +                                    {option}
The autocomplete box overlaps on the search box

![image](https://user-images.githubusercontent.com/31973210/124179994-68860680-da68-11eb-98f5-6e03ab22f514.png)

2021-07-01 20:05 UTC, HGoyal09 commented on src/components/StockTable/index.jsx
> +    const TableData = () => {
In this setup the TableData should be outside the StockTable function since it does not need to be re-computed on each re-render. There are no common state variables used in this component

2021-07-01 20:05 UTC, HGoyal09 commented on src/components/StockTable/index.jsx
> +        return stocks.map((stock, index) => {
MINOR - Replace {} with () and remove the return keyword

2021-07-01 20:05 UTC, HGoyal09 commented on src/components/StockTable/index.jsx
> +            return (
MINOR - Replace {} with () and remove the return keyword

2021-07-01 20:05 UTC, HGoyal09 commented on src/components/StockTable/index.jsx
> +    return (
MINOR - Same with this return keyword after the TableData is move out

2021-07-01 20:05 UTC, HGoyal09 commented on src/hooks/useStockInfo.jsx
> +const StockInfoProvider = ({children}) => {
Please pull the latest changes 
I am not sure why this file is here when it is already present under the contexts folder

2021-07-05 00:35 UTC, paulsgh commented
Besides what Himanshu has mentioned, I believe the tables aren't resizing as discussed. iirc, we want to pin the symbol and watchlist btn columns so they're visible no matter the screen size right?

also the table rows and the search bar leak out of their respective divs

![resizing](https://user-images.githubusercontent.com/51832617/124404108-4998a600-dcee-11eb-9f61-1ae4265a4827.png)

2021-07-05 00:41 UTC, paulsgh requested changes
Besides what Himanshu has mentioned, I believe the tables aren't resizing as discussed. iirc, we want to pin the symbol and watchlist btn columns so they're visible no matter the screen size right?

also the table rows and the search bar leak out of their respective divs

![resizing](https://user-images.githubusercontent.com/51832617/124404261-11de2e00-dcef-11eb-94e1-08862e5dd47b.png)

2021-07-07 23:06 UTC, raghavthakur commented on src/components/StockTable/index.jsx
> +                        <Th></Th>
Fixed.

2021-07-07 23:06 UTC, raghavthakur commented on src/components/StockTable/index.jsx
> +    const TableData = () => {
TableData depends on stockInfo.

2021-07-07 23:10 UTC, raghavthakur commented
Resolved most of the issues. Need to merge with the latest changes first so I can connect the backend and then resolve the minor issues.
![Screen Shot 2021-07-07 at 4 03 51 PM](https://user-images.githubusercontent.com/7005506/124839568-de451300-df3d-11eb-9d58-0d6e0cdacb24.png)

2021-07-07 23:11 UTC, closed without merging

2021-07-08 00:40 UTC, raghavthakur commented on src/components/StockTable/index.jsx
> +    const stocks = stockInfo;
Will be using context API once it's merged to progress-4 so I have the latest code.

2021-07-08 00:41 UTC, raghavthakur commented on src/components/WatchlistButton/index.jsx
> +        <Button leftIcon={<BsStar />} colorScheme='green' variant='outline' />
Resolved.

2021-07-08 00:41 UTC, raghavthakur commented on src/components/StockSearchBar/index.jsx
> +                                    {option}
Going to rewrite code once I have the backend up and running.